/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./AuctionEnglish.client";
import * as _2 from "./AuctionEnglish.message-composer";
import * as _4 from "./MarketplaceLegacy.client";
import * as _5 from "./MarketplaceLegacy.message-composer";
import * as _7 from "./MarketplaceV2.client";
import * as _8 from "./MarketplaceV2.message-composer";
import * as _10 from "./MinterMetadataOnChain.client";
import * as _11 from "./MinterMetadataOnChain.message-composer";
import * as _13 from "./Minter.client";
import * as _14 from "./Minter.message-composer";
import * as _16 from "./Pg721.client";
import * as _17 from "./Pg721.message-composer";
import * as _19 from "./PG721Legacy.client";
import * as _20 from "./PG721Legacy.message-composer";
import * as _22 from "./PG721MetadataOnChain.client";
import * as _23 from "./PG721MetadataOnChain.message-composer";
import * as _25 from "./RoyaltyGroup.client";
import * as _26 from "./RoyaltyGroup.message-composer";
import * as _28 from "./Whitelist.client";
import * as _29 from "./Whitelist.message-composer";
export declare namespace contracts {
    const AuctionEnglish: {
        AuctionEnglishMsgComposer: typeof _2.AuctionEnglishMsgComposer;
        AuctionEnglishQueryClient: typeof _1.AuctionEnglishQueryClient;
        AuctionEnglishClient: typeof _1.AuctionEnglishClient;
    };
    const MarketplaceLegacy: {
        MarketplaceLegacyMsgComposer: typeof _5.MarketplaceLegacyMsgComposer;
        MarketplaceLegacyQueryClient: typeof _4.MarketplaceLegacyQueryClient;
        MarketplaceLegacyClient: typeof _4.MarketplaceLegacyClient;
    };
    const MarketplaceV2: {
        MarketplaceV2MsgComposer: typeof _8.MarketplaceV2MsgComposer;
        MarketplaceV2QueryClient: typeof _7.MarketplaceV2QueryClient;
        MarketplaceV2Client: typeof _7.MarketplaceV2Client;
    };
    const MinterMetadataOnChain: {
        MinterMetadataOnChainMsgComposer: typeof _11.MinterMetadataOnChainMsgComposer;
        MinterMetadataOnChainQueryClient: typeof _10.MinterMetadataOnChainQueryClient;
        MinterMetadataOnChainClient: typeof _10.MinterMetadataOnChainClient;
    };
    const Minter: {
        MinterMsgComposer: typeof _14.MinterMsgComposer;
        MinterQueryClient: typeof _13.MinterQueryClient;
        MinterClient: typeof _13.MinterClient;
    };
    const Pg721: {
        Pg721MsgComposer: typeof _17.Pg721MsgComposer;
        Pg721QueryClient: typeof _16.Pg721QueryClient;
        Pg721Client: typeof _16.Pg721Client;
    };
    const PG721Legacy: {
        PG721LegacyMsgComposer: typeof _20.PG721LegacyMsgComposer;
        PG721LegacyQueryClient: typeof _19.PG721LegacyQueryClient;
        PG721LegacyClient: typeof _19.PG721LegacyClient;
    };
    const PG721MetadataOnChain: {
        PG721MetadataOnChainMsgComposer: typeof _23.PG721MetadataOnChainMsgComposer;
        PG721MetadataOnChainQueryClient: typeof _22.PG721MetadataOnChainQueryClient;
        PG721MetadataOnChainClient: typeof _22.PG721MetadataOnChainClient;
    };
    const RoyaltyGroup: {
        RoyaltyGroupMsgComposer: typeof _26.RoyaltyGroupMsgComposer;
        RoyaltyGroupQueryClient: typeof _25.RoyaltyGroupQueryClient;
        RoyaltyGroupClient: typeof _25.RoyaltyGroupClient;
    };
    const Whitelist: {
        WhitelistMsgComposer: typeof _29.WhitelistMsgComposer;
        WhitelistQueryClient: typeof _28.WhitelistQueryClient;
        WhitelistClient: typeof _28.WhitelistClient;
    };
}
