/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Pg721.client";
import * as _2 from "./Pg721.message-composer";
import * as _4 from "./PG721Legacy.client";
import * as _5 from "./PG721Legacy.message-composer";
import * as _7 from "./PG721MetadataOnChain.client";
import * as _8 from "./PG721MetadataOnChain.message-composer";
import * as _10 from "./Minter.client";
import * as _11 from "./Minter.message-composer";
import * as _13 from "./RoyaltyGroup.client";
import * as _14 from "./RoyaltyGroup.message-composer";
import * as _16 from "./Whitelist.client";
import * as _17 from "./Whitelist.message-composer";
export declare namespace contracts {
    const Pg721: {
        Pg721MsgComposer: typeof _2.Pg721MsgComposer;
        Pg721QueryClient: typeof _1.Pg721QueryClient;
        Pg721Client: typeof _1.Pg721Client;
    };
    const PG721Legacy: {
        PG721LegacyMsgComposer: typeof _5.PG721LegacyMsgComposer;
        PG721LegacyQueryClient: typeof _4.PG721LegacyQueryClient;
        PG721LegacyClient: typeof _4.PG721LegacyClient;
    };
    const PG721MetadataOnChain: {
        PG721MetadataOnChainMsgComposer: typeof _8.PG721MetadataOnChainMsgComposer;
        PG721MetadataOnChainQueryClient: typeof _7.PG721MetadataOnChainQueryClient;
        PG721MetadataOnChainClient: typeof _7.PG721MetadataOnChainClient;
    };
    const Minter: {
        MinterMsgComposer: typeof _11.MinterMsgComposer;
        MinterQueryClient: typeof _10.MinterQueryClient;
        MinterClient: typeof _10.MinterClient;
    };
    const RoyaltyGroup: {
        RoyaltyGroupMsgComposer: typeof _14.RoyaltyGroupMsgComposer;
        RoyaltyGroupQueryClient: typeof _13.RoyaltyGroupQueryClient;
        RoyaltyGroupClient: typeof _13.RoyaltyGroupClient;
    };
    const Whitelist: {
        WhitelistMsgComposer: typeof _17.WhitelistMsgComposer;
        WhitelistQueryClient: typeof _16.WhitelistQueryClient;
        WhitelistClient: typeof _16.WhitelistClient;
    };
}
