/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions } from "@tanstack/react-query";
import { MarketplaceLegacyQueryClient } from "./MarketplaceLegacy.client";
export interface MarketplaceLegacyReactQuery<TResponse, TData = TResponse> {
    client: MarketplaceLegacyQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface MarketplaceLegacyListTokensOnSaleQuery<TData> extends MarketplaceLegacyReactQuery<ListTokensOnSaleResponse, TData> {
    args: {
        limit?: number;
        startAfter?: string;
    };
}
export declare function useMarketplaceLegacyListTokensOnSaleQuery<TData = ListTokensOnSaleResponse>({ client, args, options }: MarketplaceLegacyListTokensOnSaleQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyListTokensQuery<TData> extends MarketplaceLegacyReactQuery<ListTokensResponse, TData> {
    args: {
        ids: string[];
    };
}
export declare function useMarketplaceLegacyListTokensQuery<TData = ListTokensResponse>({ client, args, options }: MarketplaceLegacyListTokensQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyRangeTokensQuery<TData> extends MarketplaceLegacyReactQuery<RangeTokensResponse, TData> {
    args: {
        limit?: number;
        startAfter?: string;
    };
}
export declare function useMarketplaceLegacyRangeTokensQuery<TData = RangeTokensResponse>({ client, args, options }: MarketplaceLegacyRangeTokensQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyTokenQuery<TData> extends MarketplaceLegacyReactQuery<TokenResponse, TData> {
    args: {
        id: string;
    };
}
export declare function useMarketplaceLegacyTokenQuery<TData = TokenResponse>({ client, args, options }: MarketplaceLegacyTokenQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyConfigQuery<TData> extends MarketplaceLegacyReactQuery<ConfigResponse, TData> {
}
export declare function useMarketplaceLegacyConfigQuery<TData = ConfigResponse>({ client, options }: MarketplaceLegacyConfigQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
