/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions } from "@tanstack/react-query";
import { ConfigResponse, QueryOptionsForTokenTimestampOffset } from "./Minter.types";
import { MinterQueryClient } from "./Minter.client";
export interface MinterReactQuery<TResponse, TData = TResponse> {
    client: MinterQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface MinterVaultTokensByUnstakeTimestampQuery<TData> extends MinterReactQuery<VaultTokensByUnstakeTimestampResponse, TData> {
    args: {
        queryOptions: QueryOptionsForTokenTimestampOffset;
    };
}
export declare function useMinterVaultTokensByUnstakeTimestampQuery<TData = VaultTokensByUnstakeTimestampResponse>({ client, args, options }: MinterVaultTokensByUnstakeTimestampQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterVaultTokensByStakeTimestampQuery<TData> extends MinterReactQuery<VaultTokensByStakeTimestampResponse, TData> {
    args: {
        queryOptions: QueryOptionsForTokenTimestampOffset;
    };
}
export declare function useMinterVaultTokensByStakeTimestampQuery<TData = VaultTokensByStakeTimestampResponse>({ client, args, options }: MinterVaultTokensByStakeTimestampQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterVaultTokensByOwnerQuery<TData> extends MinterReactQuery<VaultTokensByOwnerResponse, TData> {
    args: {
        owner: string;
        queryOptions: QueryOptionsForTokenTimestampOffset;
    };
}
export declare function useMinterVaultTokensByOwnerQuery<TData = VaultTokensByOwnerResponse>({ client, args, options }: MinterVaultTokensByOwnerQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterVaultTokenQuery<TData> extends MinterReactQuery<VaultTokenResponse, TData> {
    args: {
        tokenId: string;
    };
}
export declare function useMinterVaultTokenQuery<TData = VaultTokenResponse>({ client, args, options }: MinterVaultTokenQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterWithdrawHooksQuery<TData> extends MinterReactQuery<WithdrawHooksResponse, TData> {
}
export declare function useMinterWithdrawHooksQuery<TData = WithdrawHooksResponse>({ client, options }: MinterWithdrawHooksQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterUnstakeHooksQuery<TData> extends MinterReactQuery<UnstakeHooksResponse, TData> {
}
export declare function useMinterUnstakeHooksQuery<TData = UnstakeHooksResponse>({ client, options }: MinterUnstakeHooksQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterStakeHooksQuery<TData> extends MinterReactQuery<StakeHooksResponse, TData> {
}
export declare function useMinterStakeHooksQuery<TData = StakeHooksResponse>({ client, options }: MinterStakeHooksQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MinterConfigQuery<TData> extends MinterReactQuery<ConfigResponse, TData> {
}
export declare function useMinterConfigQuery<TData = ConfigResponse>({ client, options }: MinterConfigQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
