/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Coin, AlternativeCoin } from "./Whitelist.types";
export interface WhitelistMsg {
    contractAddress: string;
    sender: string;
    updateStartTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    addMembers: ({ toAdd }: {
        toAdd: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    removeMembers: ({ toRemove }: {
        toRemove: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class WhitelistMsgComposer implements WhitelistMsg {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateStartTime: (_funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (_funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
    addMembers: ({ toAdd }: {
        toAdd: string[];
    }, _funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
    removeMembers: ({ toRemove }: {
        toRemove: string[];
    }, _funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (_funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (_funds?: AlternativeCoin[]) => MsgExecuteContractEncodeObject;
}
