/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { RoyaltyGroupClient, RoyaltyGroupQueryClient } from "./RoyaltyGroup.client";
import { RoyaltyGroupMsgComposer } from "./RoyaltyGroup.message-composer";
export class RoyaltyGroup extends ContractBase<RoyaltyGroupClient, RoyaltyGroupQueryClient, RoyaltyGroupMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, RoyaltyGroupClient, RoyaltyGroupQueryClient, RoyaltyGroupMsgComposer);
  }

}