/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Timestamp, Uint64, Uint128, ConfigResponse, Coin, Addr, Config, ExecuteMsg, AddMembersMsg, RemoveMembersMsg, InstantiateMsg, MembersResponse, QueryMsg } from "./Whitelist.types";
import { WhitelistQueryClient, WhitelistClient } from "./Whitelist.client";
export interface WhitelistReactQuery<TResponse, TData = TResponse> {
  client: WhitelistQueryClient;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface WhitelistConfigQuery<TData> extends WhitelistReactQuery<ConfigResponse, TData> {}
export function useWhitelistConfigQuery<TData = ConfigResponse>({
  client,
  options
}: WhitelistConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(["whitelistConfig", client.contractAddress], () => client.config(), options);
}
export interface WhitelistHasMemberQuery<TData> extends WhitelistReactQuery<HasMemberResponse, TData> {
  args: {
    member: string;
  };
}
export function useWhitelistHasMemberQuery<TData = HasMemberResponse>({
  client,
  args,
  options
}: WhitelistHasMemberQuery<TData>) {
  return useQuery<HasMemberResponse, Error, TData>(["whitelistHasMember", client.contractAddress, JSON.stringify(args)], () => client.hasMember({
    member: args.member
  }), options);
}
export interface WhitelistMembersQuery<TData> extends WhitelistReactQuery<MembersResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useWhitelistMembersQuery<TData = MembersResponse>({
  client,
  args,
  options
}: WhitelistMembersQuery<TData>) {
  return useQuery<MembersResponse, Error, TData>(["whitelistMembers", client.contractAddress, JSON.stringify(args)], () => client.members({
    limit: args.limit,
    startAfter: args.startAfter
  }), options);
}
export interface WhitelistIsActiveQuery<TData> extends WhitelistReactQuery<IsActiveResponse, TData> {}
export function useWhitelistIsActiveQuery<TData = IsActiveResponse>({
  client,
  options
}: WhitelistIsActiveQuery<TData>) {
  return useQuery<IsActiveResponse, Error, TData>(["whitelistIsActive", client.contractAddress], () => client.isActive(), options);
}
export interface WhitelistHasEndedQuery<TData> extends WhitelistReactQuery<HasEndedResponse, TData> {}
export function useWhitelistHasEndedQuery<TData = HasEndedResponse>({
  client,
  options
}: WhitelistHasEndedQuery<TData>) {
  return useQuery<HasEndedResponse, Error, TData>(["whitelistHasEnded", client.contractAddress], () => client.hasEnded(), options);
}
export interface WhitelistHasStartedQuery<TData> extends WhitelistReactQuery<HasStartedResponse, TData> {}
export function useWhitelistHasStartedQuery<TData = HasStartedResponse>({
  client,
  options
}: WhitelistHasStartedQuery<TData>) {
  return useQuery<HasStartedResponse, Error, TData>(["whitelistHasStarted", client.contractAddress], () => client.hasStarted(), options);
}
export interface WhitelistIncreaseMemberLimitMutation {
  client: WhitelistClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistIncreaseMemberLimitMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistIncreaseMemberLimitMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistIncreaseMemberLimitMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.increaseMemberLimit(fee, memo, funds), options);
}
export interface WhitelistUpdatePerAddressLimitMutation {
  client: WhitelistClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistUpdatePerAddressLimitMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistUpdatePerAddressLimitMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistUpdatePerAddressLimitMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updatePerAddressLimit(fee, memo, funds), options);
}
export interface WhitelistRemoveMembersMutation {
  client: WhitelistClient;
  msg: {
    toRemove: string[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistRemoveMembersMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistRemoveMembersMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistRemoveMembersMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.removeMembers(msg, fee, memo, funds), options);
}
export interface WhitelistAddMembersMutation {
  client: WhitelistClient;
  msg: {
    toAdd: string[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistAddMembersMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistAddMembersMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistAddMembersMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.addMembers(msg, fee, memo, funds), options);
}
export interface WhitelistUpdateEndTimeMutation {
  client: WhitelistClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistUpdateEndTimeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistUpdateEndTimeMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistUpdateEndTimeMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateEndTime(msg, fee, memo, funds), options);
}
export interface WhitelistUpdateStartTimeMutation {
  client: WhitelistClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useWhitelistUpdateStartTimeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, WhitelistUpdateStartTimeMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, WhitelistUpdateStartTimeMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateStartTime(msg, fee, memo, funds), options);
}