/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { useMutation, UseMutationOptions } from "@tanstack/react-query";
import { Uint128, InstantiateMsg, MinterParamsForNullable_Empty, Coin, Empty, ExecuteMsg, Decimal, Timestamp, Uint64, CreateMinterMsgForNullable_Empty, CollectionParams, CollectionInfoForRoyaltyInfoResponse, RoyaltyInfoResponse } from "./BaseFactory.types";
import { BaseFactoryClient } from "./BaseFactory.client";
export interface BaseFactoryCreateMinterMutation {
  client: BaseFactoryClient;
  msg: {
    collectionParams: CollectionParams;
    initMsg?: Empty;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBaseFactoryCreateMinterMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BaseFactoryCreateMinterMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BaseFactoryCreateMinterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.createMinter(msg, fee, memo, funds), options);
}