/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./SG721Base.types";
import * as _1 from "./SG721Base.client";
import * as _2 from "./SG721Base.message-composer";
import * as _3 from "./SG721Base.provider";
import * as _4 from "./SG721MetadataOnchain.types";
import * as _5 from "./SG721MetadataOnchain.client";
import * as _6 from "./SG721MetadataOnchain.message-composer";
import * as _7 from "./SG721MetadataOnchain.provider";
import * as _8 from "./Sg721Updatable.types";
import * as _9 from "./Sg721Updatable.client";
import * as _10 from "./Sg721Updatable.message-composer";
import * as _11 from "./Sg721Updatable.provider";
import * as _12 from "./BaseFactory.types";
import * as _13 from "./BaseFactory.client";
import * as _14 from "./BaseFactory.message-composer";
import * as _15 from "./BaseFactory.provider";
import * as _16 from "./BaseMinter.types";
import * as _17 from "./BaseMinter.client";
import * as _18 from "./BaseMinter.message-composer";
import * as _19 from "./BaseMinter.provider";
import * as _20 from "./VendingMinter.types";
import * as _21 from "./VendingMinter.client";
import * as _22 from "./VendingMinter.message-composer";
import * as _23 from "./VendingMinter.provider";
import * as _24 from "./BadKids.types";
import * as _25 from "./BadKids.client";
import * as _26 from "./BadKids.message-composer";
import * as _27 from "./BadKids.provider";
import * as _28 from "./Marketplace.types";
import * as _29 from "./Marketplace.client";
import * as _30 from "./Marketplace.message-composer";
import * as _31 from "./Marketplace.provider";
export namespace contracts {
  export const SG721Base = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const SG721MetadataOnchain = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const Sg721Updatable = { ..._8,
    ..._9,
    ..._10,
    ..._11
  };
  export const BaseFactory = { ..._12,
    ..._13,
    ..._14,
    ..._15
  };
  export const BaseMinter = { ..._16,
    ..._17,
    ..._18,
    ..._19
  };
  export const VendingMinter = { ..._20,
    ..._21,
    ..._22,
    ..._23
  };
  export const BadKids = { ..._24,
    ..._25,
    ..._26,
    ..._27
  };
  export const Marketplace = { ..._28,
    ..._29,
    ..._30,
    ..._31
  };
}