/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AuctionEnglish.types";
import * as _1 from "./AuctionEnglish.client";
import * as _2 from "./AuctionEnglish.message-composer";
import * as _3 from "./MarketplaceLegacy.types";
import * as _4 from "./MarketplaceLegacy.client";
import * as _5 from "./MarketplaceLegacy.message-composer";
import * as _6 from "./MarketplaceV2.types";
import * as _7 from "./MarketplaceV2.client";
import * as _8 from "./MarketplaceV2.message-composer";
import * as _9 from "./MinterMetadataOnChain.types";
import * as _10 from "./MinterMetadataOnChain.client";
import * as _11 from "./MinterMetadataOnChain.message-composer";
import * as _12 from "./Minter.types";
import * as _13 from "./Minter.client";
import * as _14 from "./Minter.message-composer";
import * as _15 from "./Pg721.types";
import * as _16 from "./Pg721.client";
import * as _17 from "./Pg721.message-composer";
import * as _18 from "./PG721Legacy.types";
import * as _19 from "./PG721Legacy.client";
import * as _20 from "./PG721Legacy.message-composer";
import * as _21 from "./PG721MetadataOnChain.types";
import * as _22 from "./PG721MetadataOnChain.client";
import * as _23 from "./PG721MetadataOnChain.message-composer";
import * as _24 from "./RoyaltyGroup.types";
import * as _25 from "./RoyaltyGroup.client";
import * as _26 from "./RoyaltyGroup.message-composer";
import * as _27 from "./Whitelist.types";
import * as _28 from "./Whitelist.client";
import * as _29 from "./Whitelist.message-composer";
export namespace contracts {
  export const AuctionEnglish = {
    ..._0,
    ..._1,
    ..._2
  };
  export const MarketplaceLegacy = {
    ..._3,
    ..._4,
    ..._5
  };
  export const MarketplaceV2 = {
    ..._6,
    ..._7,
    ..._8
  };
  export const MinterMetadataOnChain = {
    ..._9,
    ..._10,
    ..._11
  };
  export const Minter = {
    ..._12,
    ..._13,
    ..._14
  };
  export const Pg721 = {
    ..._15,
    ..._16,
    ..._17
  };
  export const PG721Legacy = {
    ..._18,
    ..._19,
    ..._20
  };
  export const PG721MetadataOnChain = {
    ..._21,
    ..._22,
    ..._23
  };
  export const RoyaltyGroup = {
    ..._24,
    ..._25,
    ..._26
  };
  export const Whitelist = {
    ..._27,
    ..._28,
    ..._29
  };
}