/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Pg721.types";
import * as _1 from "./Pg721.client";
import * as _2 from "./Pg721.message-composer";
import * as _3 from "./PG721Legacy.types";
import * as _4 from "./PG721Legacy.client";
import * as _5 from "./PG721Legacy.message-composer";
import * as _6 from "./PG721MetadataOnChain.types";
import * as _7 from "./PG721MetadataOnChain.client";
import * as _8 from "./PG721MetadataOnChain.message-composer";
import * as _9 from "./Minter.types";
import * as _10 from "./Minter.client";
import * as _11 from "./Minter.message-composer";
import * as _12 from "./RoyaltyGroup.types";
import * as _13 from "./RoyaltyGroup.client";
import * as _14 from "./RoyaltyGroup.message-composer";
import * as _15 from "./Whitelist.types";
import * as _16 from "./Whitelist.client";
import * as _17 from "./Whitelist.message-composer";
export namespace contracts {
  export const Pg721 = {
    ..._0,
    ..._1,
    ..._2
  };
  export const PG721Legacy = {
    ..._3,
    ..._4,
    ..._5
  };
  export const PG721MetadataOnChain = {
    ..._6,
    ..._7,
    ..._8
  };
  export const Minter = {
    ..._9,
    ..._10,
    ..._11
  };
  export const RoyaltyGroup = {
    ..._12,
    ..._13,
    ..._14
  };
  export const Whitelist = {
    ..._15,
    ..._16,
    ..._17
  };
}