/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ContractBase, IContractConstructor } from "./contractContextBase";
import { MinterClient, MinterQueryClient } from "./Minter.client";
import { MinterMsgComposer } from "./Minter.message-composer";
export declare class Minter extends ContractBase<MinterClient, MinterQueryClient, MinterMsgComposer> {
    constructor({ address, cosmWasmClient, signingCosmWasmClient }: IContractConstructor);
}
