/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee, Coin } from "@cosmjs/amino";
import { Decimal, Uint128, Token } from "./MarketplaceLegacy.types";
import { MarketplaceLegacyQueryClient, MarketplaceLegacyClient } from "./MarketplaceLegacy.client";
export interface MarketplaceLegacyReactQuery<TResponse, TData = TResponse> {
    client: MarketplaceLegacyQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface MarketplaceLegacyListTokensOnSaleQuery<TData> extends MarketplaceLegacyReactQuery<ListTokensOnSaleResponse, TData> {
    args: {
        limit?: number;
        startAfter?: string;
    };
}
export declare function useMarketplaceLegacyListTokensOnSaleQuery<TData = ListTokensOnSaleResponse>({ client, args, options }: MarketplaceLegacyListTokensOnSaleQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyListTokensQuery<TData> extends MarketplaceLegacyReactQuery<ListTokensResponse, TData> {
    args: {
        ids: string[];
    };
}
export declare function useMarketplaceLegacyListTokensQuery<TData = ListTokensResponse>({ client, args, options }: MarketplaceLegacyListTokensQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyRangeTokensQuery<TData> extends MarketplaceLegacyReactQuery<RangeTokensResponse, TData> {
    args: {
        limit?: number;
        startAfter?: string;
    };
}
export declare function useMarketplaceLegacyRangeTokensQuery<TData = RangeTokensResponse>({ client, args, options }: MarketplaceLegacyRangeTokensQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyTokenQuery<TData> extends MarketplaceLegacyReactQuery<TokenResponse, TData> {
    args: {
        id: string;
    };
}
export declare function useMarketplaceLegacyTokenQuery<TData = TokenResponse>({ client, args, options }: MarketplaceLegacyTokenQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyConfigQuery<TData> extends MarketplaceLegacyReactQuery<ConfigResponse, TData> {
}
export declare function useMarketplaceLegacyConfigQuery<TData = ConfigResponse>({ client, options }: MarketplaceLegacyConfigQuery<TData>): import("@tanstack/react-query").DefinedUseQueryResult<TData, Error>;
export interface MarketplaceLegacyUpdateConfigMutation {
    client: MarketplaceLegacyClient;
    msg: {
        admin?: string;
        allowedNative?: string;
        collectorAddr?: string;
        feePercentage?: Decimal;
        nftAddr?: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceLegacyUpdateConfigMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceLegacyUpdateConfigMutation>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<ExecuteResult, Error, MarketplaceLegacyUpdateConfigMutation, unknown>;
export interface MarketplaceLegacyUpdatePriceMutation {
    client: MarketplaceLegacyClient;
    msg: {
        price: Uint128;
        token: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceLegacyUpdatePriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceLegacyUpdatePriceMutation>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<ExecuteResult, Error, MarketplaceLegacyUpdatePriceMutation, unknown>;
export interface MarketplaceLegacyDelistTokensMutation {
    client: MarketplaceLegacyClient;
    msg: {
        tokens: string[];
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceLegacyDelistTokensMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceLegacyDelistTokensMutation>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<ExecuteResult, Error, MarketplaceLegacyDelistTokensMutation, unknown>;
export interface MarketplaceLegacyListTokensMutation {
    client: MarketplaceLegacyClient;
    msg: {
        tokens: Token[];
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceLegacyListTokensMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceLegacyListTokensMutation>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<ExecuteResult, Error, MarketplaceLegacyListTokensMutation, unknown>;
export interface MarketplaceLegacyBuyMutation {
    client: MarketplaceLegacyClient;
    msg: {
        recipient?: string;
        tokenId: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceLegacyBuyMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceLegacyBuyMutation>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<ExecuteResult, Error, MarketplaceLegacyBuyMutation, unknown>;
