/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ContractBase, IContractConstructor } from "./contractContextBase";
import { MinterMetadataOnChainClient, MinterMetadataOnChainQueryClient } from "./MinterMetadataOnChain.client";
import { MinterMetadataOnChainMsgComposer } from "./MinterMetadataOnChain.message-composer";
export declare class MinterMetadataOnChain extends ContractBase<MinterMetadataOnChainClient, MinterMetadataOnChainQueryClient, MinterMetadataOnChainMsgComposer> {
    constructor({ address, cosmWasmClient, signingCosmWasmClient }: IContractConstructor);
}
