import * as _49 from "./protobuf/any";
import * as _50 from "./protobuf/descriptor";
import * as _51 from "./protobuf/duration";
import * as _52 from "./protobuf/empty";
import * as _53 from "./protobuf/timestamp";
export declare namespace google {
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            is(o: any): o is _53.Timestamp;
            isSDK(o: any): o is _53.TimestampSDKType;
            isAmino(o: any): o is _53.TimestampAmino;
            encode(message: _53.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _53.Timestamp;
            fromPartial(object: import("../helpers").DeepPartial<_53.Timestamp>): _53.Timestamp;
            fromAmino(object: _53.TimestampAmino): _53.Timestamp;
            toAmino(message: _53.Timestamp): _53.TimestampAmino;
            fromAminoMsg(object: _53.TimestampAminoMsg): _53.Timestamp;
            fromProtoMsg(message: _53.TimestampProtoMsg): _53.Timestamp;
            toProto(message: _53.Timestamp): Uint8Array;
            toProtoMsg(message: _53.Timestamp): _53.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            is(o: any): o is _52.Empty;
            isSDK(o: any): o is _52.EmptySDKType;
            isAmino(o: any): o is _52.EmptyAmino;
            encode(_: _52.Empty, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _52.Empty;
            fromPartial(_: import("../helpers").DeepPartial<_52.Empty>): _52.Empty;
            fromAmino(_: _52.EmptyAmino): _52.Empty;
            toAmino(_: _52.Empty): _52.EmptyAmino;
            fromAminoMsg(object: _52.EmptyAminoMsg): _52.Empty;
            fromProtoMsg(message: _52.EmptyProtoMsg): _52.Empty;
            toProto(message: _52.Empty): Uint8Array;
            toProtoMsg(message: _52.Empty): _52.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            is(o: any): o is _51.Duration;
            isSDK(o: any): o is _51.DurationSDKType;
            isAmino(o: any): o is _51.DurationAmino;
            encode(message: _51.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _51.Duration;
            fromPartial(object: import("../helpers").DeepPartial<_51.Duration>): _51.Duration;
            fromAmino(object: _51.DurationAmino): _51.Duration;
            toAmino(message: _51.Duration): _51.DurationAmino;
            fromAminoMsg(object: _51.DurationAminoMsg): _51.Duration;
            fromProtoMsg(message: _51.DurationProtoMsg): _51.Duration;
            toProto(message: _51.Duration): Uint8Array;
            toProtoMsg(message: _51.Duration): _51.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _50.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _50.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _50.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _50.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _50.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _50.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _50.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _50.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _50.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _50.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _50.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _50.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _50.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _50.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _50.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _50.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _50.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _50.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _50.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _50.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _50.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _50.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _50.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _50.FieldOptions_CType;
        FieldOptions_JSType: typeof _50.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _50.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _50.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _50.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _50.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _50.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            is(o: any): o is _50.FileDescriptorSet;
            isSDK(o: any): o is _50.FileDescriptorSetSDKType;
            isAmino(o: any): o is _50.FileDescriptorSetAmino;
            encode(message: _50.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.FileDescriptorSet;
            fromPartial(object: import("../helpers").DeepPartial<_50.FileDescriptorSet>): _50.FileDescriptorSet;
            fromAmino(object: _50.FileDescriptorSetAmino): _50.FileDescriptorSet;
            toAmino(message: _50.FileDescriptorSet): _50.FileDescriptorSetAmino;
            fromAminoMsg(object: _50.FileDescriptorSetAminoMsg): _50.FileDescriptorSet;
            fromProtoMsg(message: _50.FileDescriptorSetProtoMsg): _50.FileDescriptorSet;
            toProto(message: _50.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _50.FileDescriptorSet): _50.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.FileDescriptorProto;
            isSDK(o: any): o is _50.FileDescriptorProtoSDKType;
            isAmino(o: any): o is _50.FileDescriptorProtoAmino;
            encode(message: _50.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.FileDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.FileDescriptorProto>): _50.FileDescriptorProto;
            fromAmino(object: _50.FileDescriptorProtoAmino): _50.FileDescriptorProto;
            toAmino(message: _50.FileDescriptorProto): _50.FileDescriptorProtoAmino;
            fromAminoMsg(object: _50.FileDescriptorProtoAminoMsg): _50.FileDescriptorProto;
            fromProtoMsg(message: _50.FileDescriptorProtoProtoMsg): _50.FileDescriptorProto;
            toProto(message: _50.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.FileDescriptorProto): _50.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.DescriptorProto;
            isSDK(o: any): o is _50.DescriptorProtoSDKType;
            isAmino(o: any): o is _50.DescriptorProtoAmino;
            encode(message: _50.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.DescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.DescriptorProto>): _50.DescriptorProto;
            fromAmino(object: _50.DescriptorProtoAmino): _50.DescriptorProto;
            toAmino(message: _50.DescriptorProto): _50.DescriptorProtoAmino;
            fromAminoMsg(object: _50.DescriptorProtoAminoMsg): _50.DescriptorProto;
            fromProtoMsg(message: _50.DescriptorProtoProtoMsg): _50.DescriptorProto;
            toProto(message: _50.DescriptorProto): Uint8Array;
            toProtoMsg(message: _50.DescriptorProto): _50.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            is(o: any): o is _50.DescriptorProto_ExtensionRange;
            isSDK(o: any): o is _50.DescriptorProto_ExtensionRangeSDKType;
            isAmino(o: any): o is _50.DescriptorProto_ExtensionRangeAmino;
            encode(message: _50.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.DescriptorProto_ExtensionRange;
            fromPartial(object: import("../helpers").DeepPartial<_50.DescriptorProto_ExtensionRange>): _50.DescriptorProto_ExtensionRange;
            fromAmino(object: _50.DescriptorProto_ExtensionRangeAmino): _50.DescriptorProto_ExtensionRange;
            toAmino(message: _50.DescriptorProto_ExtensionRange): _50.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _50.DescriptorProto_ExtensionRangeAminoMsg): _50.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _50.DescriptorProto_ExtensionRangeProtoMsg): _50.DescriptorProto_ExtensionRange;
            toProto(message: _50.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _50.DescriptorProto_ExtensionRange): _50.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            is(o: any): o is _50.DescriptorProto_ReservedRange;
            isSDK(o: any): o is _50.DescriptorProto_ReservedRangeSDKType;
            isAmino(o: any): o is _50.DescriptorProto_ReservedRangeAmino;
            encode(message: _50.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.DescriptorProto_ReservedRange;
            fromPartial(object: import("../helpers").DeepPartial<_50.DescriptorProto_ReservedRange>): _50.DescriptorProto_ReservedRange;
            fromAmino(object: _50.DescriptorProto_ReservedRangeAmino): _50.DescriptorProto_ReservedRange;
            toAmino(message: _50.DescriptorProto_ReservedRange): _50.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _50.DescriptorProto_ReservedRangeAminoMsg): _50.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _50.DescriptorProto_ReservedRangeProtoMsg): _50.DescriptorProto_ReservedRange;
            toProto(message: _50.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _50.DescriptorProto_ReservedRange): _50.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            is(o: any): o is _50.ExtensionRangeOptions;
            isSDK(o: any): o is _50.ExtensionRangeOptionsSDKType;
            isAmino(o: any): o is _50.ExtensionRangeOptionsAmino;
            encode(message: _50.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.ExtensionRangeOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.ExtensionRangeOptions>): _50.ExtensionRangeOptions;
            fromAmino(object: _50.ExtensionRangeOptionsAmino): _50.ExtensionRangeOptions;
            toAmino(message: _50.ExtensionRangeOptions): _50.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _50.ExtensionRangeOptionsAminoMsg): _50.ExtensionRangeOptions;
            fromProtoMsg(message: _50.ExtensionRangeOptionsProtoMsg): _50.ExtensionRangeOptions;
            toProto(message: _50.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _50.ExtensionRangeOptions): _50.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.FieldDescriptorProto;
            isSDK(o: any): o is _50.FieldDescriptorProtoSDKType;
            isAmino(o: any): o is _50.FieldDescriptorProtoAmino;
            encode(message: _50.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.FieldDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.FieldDescriptorProto>): _50.FieldDescriptorProto;
            fromAmino(object: _50.FieldDescriptorProtoAmino): _50.FieldDescriptorProto;
            toAmino(message: _50.FieldDescriptorProto): _50.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _50.FieldDescriptorProtoAminoMsg): _50.FieldDescriptorProto;
            fromProtoMsg(message: _50.FieldDescriptorProtoProtoMsg): _50.FieldDescriptorProto;
            toProto(message: _50.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.FieldDescriptorProto): _50.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.OneofDescriptorProto;
            isSDK(o: any): o is _50.OneofDescriptorProtoSDKType;
            isAmino(o: any): o is _50.OneofDescriptorProtoAmino;
            encode(message: _50.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.OneofDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.OneofDescriptorProto>): _50.OneofDescriptorProto;
            fromAmino(object: _50.OneofDescriptorProtoAmino): _50.OneofDescriptorProto;
            toAmino(message: _50.OneofDescriptorProto): _50.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _50.OneofDescriptorProtoAminoMsg): _50.OneofDescriptorProto;
            fromProtoMsg(message: _50.OneofDescriptorProtoProtoMsg): _50.OneofDescriptorProto;
            toProto(message: _50.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.OneofDescriptorProto): _50.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.EnumDescriptorProto;
            isSDK(o: any): o is _50.EnumDescriptorProtoSDKType;
            isAmino(o: any): o is _50.EnumDescriptorProtoAmino;
            encode(message: _50.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.EnumDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.EnumDescriptorProto>): _50.EnumDescriptorProto;
            fromAmino(object: _50.EnumDescriptorProtoAmino): _50.EnumDescriptorProto;
            toAmino(message: _50.EnumDescriptorProto): _50.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _50.EnumDescriptorProtoAminoMsg): _50.EnumDescriptorProto;
            fromProtoMsg(message: _50.EnumDescriptorProtoProtoMsg): _50.EnumDescriptorProto;
            toProto(message: _50.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.EnumDescriptorProto): _50.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            is(o: any): o is _50.EnumDescriptorProto_EnumReservedRange;
            isSDK(o: any): o is _50.EnumDescriptorProto_EnumReservedRangeSDKType;
            isAmino(o: any): o is _50.EnumDescriptorProto_EnumReservedRangeAmino;
            encode(message: _50.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: import("../helpers").DeepPartial<_50.EnumDescriptorProto_EnumReservedRange>): _50.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _50.EnumDescriptorProto_EnumReservedRangeAmino): _50.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _50.EnumDescriptorProto_EnumReservedRange): _50.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _50.EnumDescriptorProto_EnumReservedRangeAminoMsg): _50.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _50.EnumDescriptorProto_EnumReservedRangeProtoMsg): _50.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _50.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _50.EnumDescriptorProto_EnumReservedRange): _50.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.EnumValueDescriptorProto;
            isSDK(o: any): o is _50.EnumValueDescriptorProtoSDKType;
            isAmino(o: any): o is _50.EnumValueDescriptorProtoAmino;
            encode(message: _50.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.EnumValueDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.EnumValueDescriptorProto>): _50.EnumValueDescriptorProto;
            fromAmino(object: _50.EnumValueDescriptorProtoAmino): _50.EnumValueDescriptorProto;
            toAmino(message: _50.EnumValueDescriptorProto): _50.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _50.EnumValueDescriptorProtoAminoMsg): _50.EnumValueDescriptorProto;
            fromProtoMsg(message: _50.EnumValueDescriptorProtoProtoMsg): _50.EnumValueDescriptorProto;
            toProto(message: _50.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.EnumValueDescriptorProto): _50.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.ServiceDescriptorProto;
            isSDK(o: any): o is _50.ServiceDescriptorProtoSDKType;
            isAmino(o: any): o is _50.ServiceDescriptorProtoAmino;
            encode(message: _50.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.ServiceDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.ServiceDescriptorProto>): _50.ServiceDescriptorProto;
            fromAmino(object: _50.ServiceDescriptorProtoAmino): _50.ServiceDescriptorProto;
            toAmino(message: _50.ServiceDescriptorProto): _50.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _50.ServiceDescriptorProtoAminoMsg): _50.ServiceDescriptorProto;
            fromProtoMsg(message: _50.ServiceDescriptorProtoProtoMsg): _50.ServiceDescriptorProto;
            toProto(message: _50.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.ServiceDescriptorProto): _50.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _50.MethodDescriptorProto;
            isSDK(o: any): o is _50.MethodDescriptorProtoSDKType;
            isAmino(o: any): o is _50.MethodDescriptorProtoAmino;
            encode(message: _50.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.MethodDescriptorProto;
            fromPartial(object: import("../helpers").DeepPartial<_50.MethodDescriptorProto>): _50.MethodDescriptorProto;
            fromAmino(object: _50.MethodDescriptorProtoAmino): _50.MethodDescriptorProto;
            toAmino(message: _50.MethodDescriptorProto): _50.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _50.MethodDescriptorProtoAminoMsg): _50.MethodDescriptorProto;
            fromProtoMsg(message: _50.MethodDescriptorProtoProtoMsg): _50.MethodDescriptorProto;
            toProto(message: _50.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _50.MethodDescriptorProto): _50.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            is(o: any): o is _50.FileOptions;
            isSDK(o: any): o is _50.FileOptionsSDKType;
            isAmino(o: any): o is _50.FileOptionsAmino;
            encode(message: _50.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.FileOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.FileOptions>): _50.FileOptions;
            fromAmino(object: _50.FileOptionsAmino): _50.FileOptions;
            toAmino(message: _50.FileOptions): _50.FileOptionsAmino;
            fromAminoMsg(object: _50.FileOptionsAminoMsg): _50.FileOptions;
            fromProtoMsg(message: _50.FileOptionsProtoMsg): _50.FileOptions;
            toProto(message: _50.FileOptions): Uint8Array;
            toProtoMsg(message: _50.FileOptions): _50.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            is(o: any): o is _50.MessageOptions;
            isSDK(o: any): o is _50.MessageOptionsSDKType;
            isAmino(o: any): o is _50.MessageOptionsAmino;
            encode(message: _50.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.MessageOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.MessageOptions>): _50.MessageOptions;
            fromAmino(object: _50.MessageOptionsAmino): _50.MessageOptions;
            toAmino(message: _50.MessageOptions): _50.MessageOptionsAmino;
            fromAminoMsg(object: _50.MessageOptionsAminoMsg): _50.MessageOptions;
            fromProtoMsg(message: _50.MessageOptionsProtoMsg): _50.MessageOptions;
            toProto(message: _50.MessageOptions): Uint8Array;
            toProtoMsg(message: _50.MessageOptions): _50.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            is(o: any): o is _50.FieldOptions;
            isSDK(o: any): o is _50.FieldOptionsSDKType;
            isAmino(o: any): o is _50.FieldOptionsAmino;
            encode(message: _50.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.FieldOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.FieldOptions>): _50.FieldOptions;
            fromAmino(object: _50.FieldOptionsAmino): _50.FieldOptions;
            toAmino(message: _50.FieldOptions): _50.FieldOptionsAmino;
            fromAminoMsg(object: _50.FieldOptionsAminoMsg): _50.FieldOptions;
            fromProtoMsg(message: _50.FieldOptionsProtoMsg): _50.FieldOptions;
            toProto(message: _50.FieldOptions): Uint8Array;
            toProtoMsg(message: _50.FieldOptions): _50.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            is(o: any): o is _50.OneofOptions;
            isSDK(o: any): o is _50.OneofOptionsSDKType;
            isAmino(o: any): o is _50.OneofOptionsAmino;
            encode(message: _50.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.OneofOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.OneofOptions>): _50.OneofOptions;
            fromAmino(object: _50.OneofOptionsAmino): _50.OneofOptions;
            toAmino(message: _50.OneofOptions): _50.OneofOptionsAmino;
            fromAminoMsg(object: _50.OneofOptionsAminoMsg): _50.OneofOptions;
            fromProtoMsg(message: _50.OneofOptionsProtoMsg): _50.OneofOptions;
            toProto(message: _50.OneofOptions): Uint8Array;
            toProtoMsg(message: _50.OneofOptions): _50.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            is(o: any): o is _50.EnumOptions;
            isSDK(o: any): o is _50.EnumOptionsSDKType;
            isAmino(o: any): o is _50.EnumOptionsAmino;
            encode(message: _50.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.EnumOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.EnumOptions>): _50.EnumOptions;
            fromAmino(object: _50.EnumOptionsAmino): _50.EnumOptions;
            toAmino(message: _50.EnumOptions): _50.EnumOptionsAmino;
            fromAminoMsg(object: _50.EnumOptionsAminoMsg): _50.EnumOptions;
            fromProtoMsg(message: _50.EnumOptionsProtoMsg): _50.EnumOptions;
            toProto(message: _50.EnumOptions): Uint8Array;
            toProtoMsg(message: _50.EnumOptions): _50.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            is(o: any): o is _50.EnumValueOptions;
            isSDK(o: any): o is _50.EnumValueOptionsSDKType;
            isAmino(o: any): o is _50.EnumValueOptionsAmino;
            encode(message: _50.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.EnumValueOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.EnumValueOptions>): _50.EnumValueOptions;
            fromAmino(object: _50.EnumValueOptionsAmino): _50.EnumValueOptions;
            toAmino(message: _50.EnumValueOptions): _50.EnumValueOptionsAmino;
            fromAminoMsg(object: _50.EnumValueOptionsAminoMsg): _50.EnumValueOptions;
            fromProtoMsg(message: _50.EnumValueOptionsProtoMsg): _50.EnumValueOptions;
            toProto(message: _50.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _50.EnumValueOptions): _50.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            is(o: any): o is _50.ServiceOptions;
            isSDK(o: any): o is _50.ServiceOptionsSDKType;
            isAmino(o: any): o is _50.ServiceOptionsAmino;
            encode(message: _50.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.ServiceOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.ServiceOptions>): _50.ServiceOptions;
            fromAmino(object: _50.ServiceOptionsAmino): _50.ServiceOptions;
            toAmino(message: _50.ServiceOptions): _50.ServiceOptionsAmino;
            fromAminoMsg(object: _50.ServiceOptionsAminoMsg): _50.ServiceOptions;
            fromProtoMsg(message: _50.ServiceOptionsProtoMsg): _50.ServiceOptions;
            toProto(message: _50.ServiceOptions): Uint8Array;
            toProtoMsg(message: _50.ServiceOptions): _50.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            is(o: any): o is _50.MethodOptions;
            isSDK(o: any): o is _50.MethodOptionsSDKType;
            isAmino(o: any): o is _50.MethodOptionsAmino;
            encode(message: _50.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.MethodOptions;
            fromPartial(object: import("../helpers").DeepPartial<_50.MethodOptions>): _50.MethodOptions;
            fromAmino(object: _50.MethodOptionsAmino): _50.MethodOptions;
            toAmino(message: _50.MethodOptions): _50.MethodOptionsAmino;
            fromAminoMsg(object: _50.MethodOptionsAminoMsg): _50.MethodOptions;
            fromProtoMsg(message: _50.MethodOptionsProtoMsg): _50.MethodOptions;
            toProto(message: _50.MethodOptions): Uint8Array;
            toProtoMsg(message: _50.MethodOptions): _50.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            is(o: any): o is _50.UninterpretedOption;
            isSDK(o: any): o is _50.UninterpretedOptionSDKType;
            isAmino(o: any): o is _50.UninterpretedOptionAmino;
            encode(message: _50.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.UninterpretedOption;
            fromPartial(object: import("../helpers").DeepPartial<_50.UninterpretedOption>): _50.UninterpretedOption;
            fromAmino(object: _50.UninterpretedOptionAmino): _50.UninterpretedOption;
            toAmino(message: _50.UninterpretedOption): _50.UninterpretedOptionAmino;
            fromAminoMsg(object: _50.UninterpretedOptionAminoMsg): _50.UninterpretedOption;
            fromProtoMsg(message: _50.UninterpretedOptionProtoMsg): _50.UninterpretedOption;
            toProto(message: _50.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _50.UninterpretedOption): _50.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            is(o: any): o is _50.UninterpretedOption_NamePart;
            isSDK(o: any): o is _50.UninterpretedOption_NamePartSDKType;
            isAmino(o: any): o is _50.UninterpretedOption_NamePartAmino;
            encode(message: _50.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.UninterpretedOption_NamePart;
            fromPartial(object: import("../helpers").DeepPartial<_50.UninterpretedOption_NamePart>): _50.UninterpretedOption_NamePart;
            fromAmino(object: _50.UninterpretedOption_NamePartAmino): _50.UninterpretedOption_NamePart;
            toAmino(message: _50.UninterpretedOption_NamePart): _50.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _50.UninterpretedOption_NamePartAminoMsg): _50.UninterpretedOption_NamePart;
            fromProtoMsg(message: _50.UninterpretedOption_NamePartProtoMsg): _50.UninterpretedOption_NamePart;
            toProto(message: _50.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _50.UninterpretedOption_NamePart): _50.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            is(o: any): o is _50.SourceCodeInfo;
            isSDK(o: any): o is _50.SourceCodeInfoSDKType;
            isAmino(o: any): o is _50.SourceCodeInfoAmino;
            encode(message: _50.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.SourceCodeInfo;
            fromPartial(object: import("../helpers").DeepPartial<_50.SourceCodeInfo>): _50.SourceCodeInfo;
            fromAmino(object: _50.SourceCodeInfoAmino): _50.SourceCodeInfo;
            toAmino(message: _50.SourceCodeInfo): _50.SourceCodeInfoAmino;
            fromAminoMsg(object: _50.SourceCodeInfoAminoMsg): _50.SourceCodeInfo;
            fromProtoMsg(message: _50.SourceCodeInfoProtoMsg): _50.SourceCodeInfo;
            toProto(message: _50.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _50.SourceCodeInfo): _50.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            is(o: any): o is _50.SourceCodeInfo_Location;
            isSDK(o: any): o is _50.SourceCodeInfo_LocationSDKType;
            isAmino(o: any): o is _50.SourceCodeInfo_LocationAmino;
            encode(message: _50.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.SourceCodeInfo_Location;
            fromPartial(object: import("../helpers").DeepPartial<_50.SourceCodeInfo_Location>): _50.SourceCodeInfo_Location;
            fromAmino(object: _50.SourceCodeInfo_LocationAmino): _50.SourceCodeInfo_Location;
            toAmino(message: _50.SourceCodeInfo_Location): _50.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _50.SourceCodeInfo_LocationAminoMsg): _50.SourceCodeInfo_Location;
            fromProtoMsg(message: _50.SourceCodeInfo_LocationProtoMsg): _50.SourceCodeInfo_Location;
            toProto(message: _50.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _50.SourceCodeInfo_Location): _50.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            is(o: any): o is _50.GeneratedCodeInfo;
            isSDK(o: any): o is _50.GeneratedCodeInfoSDKType;
            isAmino(o: any): o is _50.GeneratedCodeInfoAmino;
            encode(message: _50.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.GeneratedCodeInfo;
            fromPartial(object: import("../helpers").DeepPartial<_50.GeneratedCodeInfo>): _50.GeneratedCodeInfo;
            fromAmino(object: _50.GeneratedCodeInfoAmino): _50.GeneratedCodeInfo;
            toAmino(message: _50.GeneratedCodeInfo): _50.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _50.GeneratedCodeInfoAminoMsg): _50.GeneratedCodeInfo;
            fromProtoMsg(message: _50.GeneratedCodeInfoProtoMsg): _50.GeneratedCodeInfo;
            toProto(message: _50.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _50.GeneratedCodeInfo): _50.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            is(o: any): o is _50.GeneratedCodeInfo_Annotation;
            isSDK(o: any): o is _50.GeneratedCodeInfo_AnnotationSDKType;
            isAmino(o: any): o is _50.GeneratedCodeInfo_AnnotationAmino;
            encode(message: _50.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _50.GeneratedCodeInfo_Annotation;
            fromPartial(object: import("../helpers").DeepPartial<_50.GeneratedCodeInfo_Annotation>): _50.GeneratedCodeInfo_Annotation;
            fromAmino(object: _50.GeneratedCodeInfo_AnnotationAmino): _50.GeneratedCodeInfo_Annotation;
            toAmino(message: _50.GeneratedCodeInfo_Annotation): _50.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _50.GeneratedCodeInfo_AnnotationAminoMsg): _50.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _50.GeneratedCodeInfo_AnnotationProtoMsg): _50.GeneratedCodeInfo_Annotation;
            toProto(message: _50.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _50.GeneratedCodeInfo_Annotation): _50.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            is(o: any): o is _49.Any;
            isSDK(o: any): o is _49.AnySDKType;
            isAmino(o: any): o is _49.AnyAmino;
            encode(message: _49.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _49.Any;
            fromPartial(object: import("../helpers").DeepPartial<_49.Any>): _49.Any;
            fromAmino(object: _49.AnyAmino): _49.Any;
            toAmino(message: _49.Any): _49.AnyAmino;
            fromAminoMsg(object: _49.AnyAminoMsg): _49.Any;
            fromProtoMsg(message: _49.AnyProtoMsg): _49.Any;
            toProto(message: _49.Any): Uint8Array;
            toProtoMsg(message: _49.Any): _49.AnyProtoMsg;
        };
    };
}
