/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./SG721Base.client";
import * as _3 from "./SG721Base.provider";
import * as _5 from "./SG721MetadataOnchain.client";
import * as _7 from "./SG721MetadataOnchain.provider";
import * as _9 from "./Sg721Updatable.client";
import * as _10 from "./Sg721Updatable.message-composer";
import * as _11 from "./Sg721Updatable.provider";
import * as _13 from "./BaseFactory.client";
import * as _14 from "./BaseFactory.message-composer";
import * as _15 from "./BaseFactory.provider";
import * as _17 from "./BaseMinter.client";
import * as _18 from "./BaseMinter.message-composer";
import * as _19 from "./BaseMinter.provider";
import * as _21 from "./VendingMinter.client";
import * as _22 from "./VendingMinter.message-composer";
import * as _23 from "./VendingMinter.provider";
import * as _25 from "./BadKids.client";
import * as _26 from "./BadKids.message-composer";
import * as _27 from "./BadKids.provider";
import * as _29 from "./Marketplace.client";
import * as _30 from "./Marketplace.message-composer";
import * as _31 from "./Marketplace.provider";
export declare namespace contracts {
    const SG721Base: {
        SG721Base: typeof _3.SG721Base;
        SG721BaseQueryClient: typeof _1.SG721BaseQueryClient;
    };
    const SG721MetadataOnchain: {
        SG721MetadataOnchain: typeof _7.SG721MetadataOnchain;
        SG721MetadataOnchainQueryClient: typeof _5.SG721MetadataOnchainQueryClient;
    };
    const Sg721Updatable: {
        Sg721Updatable: typeof _11.Sg721Updatable;
        Sg721UpdatableMessageComposer: typeof _10.Sg721UpdatableMessageComposer;
        Sg721UpdatableQueryClient: typeof _9.Sg721UpdatableQueryClient;
        Sg721UpdatableClient: typeof _9.Sg721UpdatableClient;
    };
    const BaseFactory: {
        BaseFactory: typeof _15.BaseFactory;
        BaseFactoryMessageComposer: typeof _14.BaseFactoryMessageComposer;
        BaseFactoryClient: typeof _13.BaseFactoryClient;
    };
    const BaseMinter: {
        BaseMinter: typeof _19.BaseMinter;
        BaseMinterMessageComposer: typeof _18.BaseMinterMessageComposer;
        BaseMinterClient: typeof _17.BaseMinterClient;
    };
    const VendingMinter: {
        VendingMinter: typeof _23.VendingMinter;
        VendingMinterMessageComposer: typeof _22.VendingMinterMessageComposer;
        VendingMinterQueryClient: typeof _21.VendingMinterQueryClient;
        VendingMinterClient: typeof _21.VendingMinterClient;
    };
    const BadKids: {
        BadKids: typeof _27.BadKids;
        BadKidsMessageComposer: typeof _26.BadKidsMessageComposer;
        BadKidsQueryClient: typeof _25.BadKidsQueryClient;
        BadKidsClient: typeof _25.BadKidsClient;
    };
    const Marketplace: {
        Marketplace: typeof _31.Marketplace;
        MarketplaceMessageComposer: typeof _30.MarketplaceMessageComposer;
        MarketplaceQueryClient: typeof _29.MarketplaceQueryClient;
        MarketplaceClient: typeof _29.MarketplaceClient;
    };
}
