/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Timestamp, SaleType, Coin, AskOffset, CollectionOffset, BidOffset, CollectionBidOffset, AsksResponse, AskCountResponse, HooksResponse, BidResponse, BidsResponse, CollectionBidResponse, CollectionsResponse, ParamsResponse } from "./Marketplace.types";
import { MarketplaceQueryClient, MarketplaceClient } from "./Marketplace.client";
export interface MarketplaceReactQuery<TResponse, TData = TResponse> {
    client: MarketplaceQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface MarketplaceParamsQuery<TData> extends MarketplaceReactQuery<ParamsResponse, TData> {
}
export declare function useMarketplaceParamsQuery<TData = ParamsResponse>({ client, options }: MarketplaceParamsQuery<TData>): any;
export interface MarketplaceSaleHooksQuery<TData> extends MarketplaceReactQuery<HooksResponse, TData> {
}
export declare function useMarketplaceSaleHooksQuery<TData = HooksResponse>({ client, options }: MarketplaceSaleHooksQuery<TData>): any;
export interface MarketplaceBidHooksQuery<TData> extends MarketplaceReactQuery<HooksResponse, TData> {
}
export declare function useMarketplaceBidHooksQuery<TData = HooksResponse>({ client, options }: MarketplaceBidHooksQuery<TData>): any;
export interface MarketplaceAskHooksQuery<TData> extends MarketplaceReactQuery<HooksResponse, TData> {
}
export declare function useMarketplaceAskHooksQuery<TData = HooksResponse>({ client, options }: MarketplaceAskHooksQuery<TData>): any;
export interface MarketplaceReverseCollectionBidsSortedByPriceQuery<TData> extends MarketplaceReactQuery<CollectionBidResponse, TData> {
    args: {
        collection: string;
        limit?: number;
        startBefore?: CollectionBidOffset;
    };
}
export declare function useMarketplaceReverseCollectionBidsSortedByPriceQuery<TData = CollectionBidResponse>({ client, args, options }: MarketplaceReverseCollectionBidsSortedByPriceQuery<TData>): any;
export interface MarketplaceCollectionBidsSortedByPriceQuery<TData> extends MarketplaceReactQuery<CollectionBidResponse, TData> {
    args: {
        collection: string;
        limit?: number;
        startAfter?: CollectionBidOffset;
    };
}
export declare function useMarketplaceCollectionBidsSortedByPriceQuery<TData = CollectionBidResponse>({ client, args, options }: MarketplaceCollectionBidsSortedByPriceQuery<TData>): any;
export interface MarketplaceCollectionBidsByBidderSortedByExpirationQuery<TData> extends MarketplaceReactQuery<CollectionBidResponse, TData> {
    args: {
        bidder: string;
        limit?: number;
        startAfter?: CollectionBidOffset;
    };
}
export declare function useMarketplaceCollectionBidsByBidderSortedByExpirationQuery<TData = CollectionBidResponse>({ client, args, options }: MarketplaceCollectionBidsByBidderSortedByExpirationQuery<TData>): any;
export interface MarketplaceCollectionBidsByBidderQuery<TData> extends MarketplaceReactQuery<CollectionBidResponse, TData> {
    args: {
        bidder: string;
        limit?: number;
        startAfter?: CollectionOffset;
    };
}
export declare function useMarketplaceCollectionBidsByBidderQuery<TData = CollectionBidResponse>({ client, args, options }: MarketplaceCollectionBidsByBidderQuery<TData>): any;
export interface MarketplaceCollectionBidQuery<TData> extends MarketplaceReactQuery<CollectionBidResponse, TData> {
    args: {
        bidder: string;
        collection: string;
    };
}
export declare function useMarketplaceCollectionBidQuery<TData = CollectionBidResponse>({ client, args, options }: MarketplaceCollectionBidQuery<TData>): any;
export interface MarketplaceReverseBidsSortedByPriceQuery<TData> extends MarketplaceReactQuery<BidsResponse, TData> {
    args: {
        collection: string;
        limit?: number;
        startBefore?: BidOffset;
    };
}
export declare function useMarketplaceReverseBidsSortedByPriceQuery<TData = BidsResponse>({ client, args, options }: MarketplaceReverseBidsSortedByPriceQuery<TData>): any;
export interface MarketplaceBidsSortedByPriceQuery<TData> extends MarketplaceReactQuery<BidsResponse, TData> {
    args: {
        collection: string;
        limit?: number;
        startAfter?: BidOffset;
    };
}
export declare function useMarketplaceBidsSortedByPriceQuery<TData = BidsResponse>({ client, args, options }: MarketplaceBidsSortedByPriceQuery<TData>): any;
export interface MarketplaceBidsQuery<TData> extends MarketplaceReactQuery<BidsResponse, TData> {
    args: {
        collection: string;
        limit?: number;
        startAfter?: string;
        tokenId: number;
    };
}
export declare function useMarketplaceBidsQuery<TData = BidsResponse>({ client, args, options }: MarketplaceBidsQuery<TData>): any;
export interface MarketplaceBidsByBidderSortedByExpirationQuery<TData> extends MarketplaceReactQuery<BidsResponse, TData> {
    args: {
        bidder: string;
        limit?: number;
        startAfter?: CollectionOffset;
    };
}
export declare function useMarketplaceBidsByBidderSortedByExpirationQuery<TData = BidsResponse>({ client, args, options }: MarketplaceBidsByBidderSortedByExpirationQuery<TData>): any;
export interface MarketplaceBidsByBidderQuery<TData> extends MarketplaceReactQuery<BidsResponse, TData> {
    args: {
        bidder: string;
        limit?: number;
        startAfter?: CollectionOffset;
    };
}
export declare function useMarketplaceBidsByBidderQuery<TData = BidsResponse>({ client, args, options }: MarketplaceBidsByBidderQuery<TData>): any;
export interface MarketplaceBidQuery<TData> extends MarketplaceReactQuery<BidResponse, TData> {
    args: {
        bidder: string;
        collection: string;
        tokenId: number;
    };
}
export declare function useMarketplaceBidQuery<TData = BidResponse>({ client, args, options }: MarketplaceBidQuery<TData>): any;
export interface MarketplaceAsksBySellerQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        includeInactive?: boolean;
        limit?: number;
        seller: string;
        startAfter?: CollectionOffset;
    };
}
export declare function useMarketplaceAsksBySellerQuery<TData = AsksResponse>({ client, args, options }: MarketplaceAsksBySellerQuery<TData>): any;
export interface MarketplaceAskCountQuery<TData> extends MarketplaceReactQuery<AskCountResponse, TData> {
    args: {
        collection: string;
    };
}
export declare function useMarketplaceAskCountQuery<TData = AskCountResponse>({ client, args, options }: MarketplaceAskCountQuery<TData>): any;
export interface MarketplaceReverseAsksSortedByPriceQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        collection: string;
        includeInactive?: boolean;
        limit?: number;
        startBefore?: AskOffset;
    };
}
export declare function useMarketplaceReverseAsksSortedByPriceQuery<TData = AsksResponse>({ client, args, options }: MarketplaceReverseAsksSortedByPriceQuery<TData>): any;
export interface MarketplaceAsksSortedByPriceQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        collection: string;
        includeInactive?: boolean;
        limit?: number;
        startAfter?: AskOffset;
    };
}
export declare function useMarketplaceAsksSortedByPriceQuery<TData = AsksResponse>({ client, args, options }: MarketplaceAsksSortedByPriceQuery<TData>): any;
export interface MarketplaceReverseAsksQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        collection: string;
        includeInactive?: boolean;
        limit?: number;
        startBefore?: number;
    };
}
export declare function useMarketplaceReverseAsksQuery<TData = AsksResponse>({ client, args, options }: MarketplaceReverseAsksQuery<TData>): any;
export interface MarketplaceAsksQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        collection: string;
        includeInactive?: boolean;
        limit?: number;
        startAfter?: number;
    };
}
export declare function useMarketplaceAsksQuery<TData = AsksResponse>({ client, args, options }: MarketplaceAsksQuery<TData>): any;
export interface MarketplaceAskQuery<TData> extends MarketplaceReactQuery<AsksResponse, TData> {
    args: {
        collection: string;
        tokenId: number;
    };
}
export declare function useMarketplaceAskQuery<TData = AsksResponse>({ client, args, options }: MarketplaceAskQuery<TData>): any;
export interface MarketplaceCollectionsQuery<TData> extends MarketplaceReactQuery<CollectionsResponse, TData> {
    args: {
        limit?: number;
        startAfter?: string;
    };
}
export declare function useMarketplaceCollectionsQuery<TData = CollectionsResponse>({ client, args, options }: MarketplaceCollectionsQuery<TData>): any;
export interface MarketplaceRemoveStaleCollectionBidMutation {
    client: MarketplaceClient;
    msg: {
        bidder: string;
        collection: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveStaleCollectionBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveStaleCollectionBidMutation>, "mutationFn">): any;
export interface MarketplaceRemoveStaleBidMutation {
    client: MarketplaceClient;
    msg: {
        bidder: string;
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveStaleBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveStaleBidMutation>, "mutationFn">): any;
export interface MarketplaceRemoveStaleAskMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveStaleAskMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveStaleAskMutation>, "mutationFn">): any;
export interface MarketplaceSyncAskMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceSyncAskMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceSyncAskMutation>, "mutationFn">): any;
export interface MarketplaceAcceptCollectionBidMutation {
    client: MarketplaceClient;
    msg: {
        bidder: string;
        collection: string;
        finder?: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceAcceptCollectionBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceAcceptCollectionBidMutation>, "mutationFn">): any;
export interface MarketplaceRemoveCollectionBidMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveCollectionBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveCollectionBidMutation>, "mutationFn">): any;
export interface MarketplaceSetCollectionBidMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        expires: Timestamp;
        findersFeeBps?: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceSetCollectionBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceSetCollectionBidMutation>, "mutationFn">): any;
export interface MarketplaceRejectBidMutation {
    client: MarketplaceClient;
    msg: {
        bidder: string;
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRejectBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRejectBidMutation>, "mutationFn">): any;
export interface MarketplaceAcceptBidMutation {
    client: MarketplaceClient;
    msg: {
        bidder: string;
        collection: string;
        finder?: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceAcceptBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceAcceptBidMutation>, "mutationFn">): any;
export interface MarketplaceRemoveBidMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveBidMutation>, "mutationFn">): any;
export interface MarketplaceBuyNowMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        expires: Timestamp;
        finder?: string;
        findersFeeBps?: number;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceBuyNowMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceBuyNowMutation>, "mutationFn">): any;
export interface MarketplaceSetBidMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        expires: Timestamp;
        finder?: string;
        findersFeeBps?: number;
        saleType: SaleType;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceSetBidMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceSetBidMutation>, "mutationFn">): any;
export interface MarketplaceUpdateAskPriceMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        price: Coin;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceUpdateAskPriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceUpdateAskPriceMutation>, "mutationFn">): any;
export interface MarketplaceRemoveAskMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceRemoveAskMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceRemoveAskMutation>, "mutationFn">): any;
export interface MarketplaceSetAskMutation {
    client: MarketplaceClient;
    msg: {
        collection: string;
        expires: Timestamp;
        findersFeeBps?: number;
        fundsRecipient?: string;
        price: Coin;
        reserveFor?: string;
        saleType: SaleType;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useMarketplaceSetAskMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, MarketplaceSetAskMutation>, "mutationFn">): any;
