/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { ConfigResponse, Coin, MintCountResponse, MintPriceResponse, MintableNumTokensResponse, StartTimeResponse, StatusResponse } from "./VendingMinter.types";
import { VendingMinterQueryClient, VendingMinterClient } from "./VendingMinter.client";
export interface VendingMinterReactQuery<TResponse, TData = TResponse> {
    client: VendingMinterQueryClient;
    options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
        initialData?: undefined;
    };
}
export interface VendingMinterStatusQuery<TData> extends VendingMinterReactQuery<StatusResponse, TData> {
}
export declare function useVendingMinterStatusQuery<TData = StatusResponse>({ client, options }: VendingMinterStatusQuery<TData>): any;
export interface VendingMinterMintCountQuery<TData> extends VendingMinterReactQuery<MintCountResponse, TData> {
    args: {
        address: string;
    };
}
export declare function useVendingMinterMintCountQuery<TData = MintCountResponse>({ client, args, options }: VendingMinterMintCountQuery<TData>): any;
export interface VendingMinterMintPriceQuery<TData> extends VendingMinterReactQuery<MintPriceResponse, TData> {
}
export declare function useVendingMinterMintPriceQuery<TData = MintPriceResponse>({ client, options }: VendingMinterMintPriceQuery<TData>): any;
export interface VendingMinterStartTimeQuery<TData> extends VendingMinterReactQuery<StartTimeResponse, TData> {
}
export declare function useVendingMinterStartTimeQuery<TData = StartTimeResponse>({ client, options }: VendingMinterStartTimeQuery<TData>): any;
export interface VendingMinterMintableNumTokensQuery<TData> extends VendingMinterReactQuery<MintableNumTokensResponse, TData> {
}
export declare function useVendingMinterMintableNumTokensQuery<TData = MintableNumTokensResponse>({ client, options }: VendingMinterMintableNumTokensQuery<TData>): any;
export interface VendingMinterConfigQuery<TData> extends VendingMinterReactQuery<ConfigResponse, TData> {
}
export declare function useVendingMinterConfigQuery<TData = ConfigResponse>({ client, options }: VendingMinterConfigQuery<TData>): any;
export interface VendingMinterRemoveDiscountPriceMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterRemoveDiscountPriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterRemoveDiscountPriceMutation>, "mutationFn">): any;
export interface VendingMinterUpdateDiscountPriceMutation {
    client: VendingMinterClient;
    msg: {
        price: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterUpdateDiscountPriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterUpdateDiscountPriceMutation>, "mutationFn">): any;
export interface VendingMinterBurnRemainingMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterBurnRemainingMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterBurnRemainingMutation>, "mutationFn">): any;
export interface VendingMinterShuffleMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterShuffleMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterShuffleMutation>, "mutationFn">): any;
export interface VendingMinterMintForMutation {
    client: VendingMinterClient;
    msg: {
        recipient: string;
        tokenId: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterMintForMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterMintForMutation>, "mutationFn">): any;
export interface VendingMinterMintToMutation {
    client: VendingMinterClient;
    msg: {
        recipient: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterMintToMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterMintToMutation>, "mutationFn">): any;
export interface VendingMinterUpdatePerAddressLimitMutation {
    client: VendingMinterClient;
    msg: {
        perAddressLimit: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterUpdatePerAddressLimitMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterUpdatePerAddressLimitMutation>, "mutationFn">): any;
export interface VendingMinterUpdateStartTradingTimeMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterUpdateStartTradingTimeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterUpdateStartTradingTimeMutation>, "mutationFn">): any;
export interface VendingMinterUpdateStartTimeMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterUpdateStartTimeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterUpdateStartTimeMutation>, "mutationFn">): any;
export interface VendingMinterUpdateMintPriceMutation {
    client: VendingMinterClient;
    msg: {
        price: number;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterUpdateMintPriceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterUpdateMintPriceMutation>, "mutationFn">): any;
export interface VendingMinterPurgeMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterPurgeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterPurgeMutation>, "mutationFn">): any;
export interface VendingMinterSetWhitelistMutation {
    client: VendingMinterClient;
    msg: {
        whitelist: string;
    };
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterSetWhitelistMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterSetWhitelistMutation>, "mutationFn">): any;
export interface VendingMinterMintMutation {
    client: VendingMinterClient;
    args?: {
        fee?: number | StdFee | "auto";
        memo?: string;
        funds?: Coin[];
    };
}
export declare function useVendingMinterMintMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, VendingMinterMintMutation>, "mutationFn">): any;
