/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AuctionEnglish.types";
import * as _1 from "./AuctionEnglish.client";
import * as _2 from "./AuctionEnglish.message-composer";
import * as _3 from "./AuctionEnglish.react-query";
import * as _4 from "./AuctionEnglish.provider";
import * as _5 from "./MarketplaceLegacy.types";
import * as _6 from "./MarketplaceLegacy.client";
import * as _7 from "./MarketplaceLegacy.message-composer";
import * as _8 from "./MarketplaceLegacy.react-query";
import * as _9 from "./MarketplaceLegacy.provider";
import * as _10 from "./MarketplaceV2.types";
import * as _11 from "./MarketplaceV2.client";
import * as _12 from "./MarketplaceV2.message-composer";
import * as _13 from "./MarketplaceV2.react-query";
import * as _14 from "./MarketplaceV2.provider";
import * as _15 from "./MinterMetadataOnChain.types";
import * as _16 from "./MinterMetadataOnChain.client";
import * as _17 from "./MinterMetadataOnChain.message-composer";
import * as _18 from "./MinterMetadataOnChain.react-query";
import * as _19 from "./MinterMetadataOnChain.provider";
import * as _20 from "./Minter.types";
import * as _21 from "./Minter.client";
import * as _22 from "./Minter.message-composer";
import * as _23 from "./Minter.react-query";
import * as _24 from "./Minter.provider";
import * as _25 from "./PG721Legacy.types";
import * as _26 from "./PG721Legacy.client";
import * as _27 from "./PG721Legacy.message-composer";
import * as _28 from "./PG721Legacy.react-query";
import * as _29 from "./PG721Legacy.provider";
import * as _30 from "./PG721Legacy.types";
import * as _31 from "./PG721Legacy.client";
import * as _32 from "./PG721Legacy.message-composer";
import * as _33 from "./PG721Legacy.react-query";
import * as _34 from "./PG721Legacy.provider";
import * as _35 from "./PG721MetadataOnChain.types";
import * as _36 from "./PG721MetadataOnChain.client";
import * as _37 from "./PG721MetadataOnChain.message-composer";
import * as _38 from "./PG721MetadataOnChain.react-query";
import * as _39 from "./PG721MetadataOnChain.provider";
import * as _40 from "./Pg721.types";
import * as _41 from "./Pg721.client";
import * as _42 from "./Pg721.message-composer";
import * as _43 from "./Pg721.react-query";
import * as _44 from "./Pg721.provider";
import * as _45 from "./RoyaltyGroup.types";
import * as _46 from "./RoyaltyGroup.client";
import * as _47 from "./RoyaltyGroup.message-composer";
import * as _48 from "./RoyaltyGroup.react-query";
import * as _49 from "./RoyaltyGroup.provider";
import * as _50 from "./Whitelist.types";
import * as _51 from "./Whitelist.client";
import * as _52 from "./Whitelist.message-composer";
import * as _53 from "./Whitelist.react-query";
import * as _54 from "./Whitelist.provider";
import * as _55 from "./contractContextProviders";
import * as _56 from "./contractContextBase";
import * as _57 from "./contracts-context";
export namespace contracts {
  export const AuctionEnglish = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
  export const MarketplaceLegacy = { ..._5,
    ..._6,
    ..._7,
    ..._8,
    ..._9
  };
  export const MarketplaceV2 = { ..._10,
    ..._11,
    ..._12,
    ..._13,
    ..._14
  };
  export const MinterMetadataOnChain = { ..._15,
    ..._16,
    ..._17,
    ..._18,
    ..._19
  };
  export const Minter = { ..._20,
    ..._21,
    ..._22,
    ..._23,
    ..._24
  };
  export const PG721Legacy = { ..._25,
    ..._26,
    ..._27,
    ..._28,
    ..._29,
    ..._30,
    ..._31,
    ..._32,
    ..._33,
    ..._34
  };
  export const PG721MetadataOnChain = { ..._35,
    ..._36,
    ..._37,
    ..._38,
    ..._39
  };
  export const Pg721 = { ..._40,
    ..._41,
    ..._42,
    ..._43,
    ..._44
  };
  export const RoyaltyGroup = { ..._45,
    ..._46,
    ..._47,
    ..._48,
    ..._49
  };
  export const Whitelist = { ..._50,
    ..._51,
    ..._52,
    ..._53,
    ..._54
  };
  export const contractContextProviders = { ..._55
  };
  export const contractContextBase = { ..._56
  };
  export const contractsContext = { ..._57
  };
}