/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { AskCountResponse, Timestamp, Uint64, Addr, Uint128, AskResponse, Ask, Coin, AsksResponse, BidResponse, Bid, BidsResponse, CollectionBidExpiryOffset, CollectionBidPriceOffset, CollectionBidResponse, CollectionBid, CollectionBidsResponse, Decimal, ConfigResponse, Config, ExpiryRange, ExecuteMsg, InstantiateMsg, MarketplaceContract, QueryMsg, QueryOptionsForTokenTimestampOffset, TokenTimestampOffset, QueryOptionsForTokenPriceOffset, TokenPriceOffset, QueryOptionsForBidExpiryOffset, BidExpiryOffset, QueryOptionsForBidTokenPriceOffset, BidTokenPriceOffset, QueryOptionsForCollectionBidPriceOffset, QueryOptionsForCollectionBidExpiryOffset } from "./MarketplaceV2.types";
import { MarketplaceV2QueryClient } from "./MarketplaceV2.client";
export interface MarketplaceV2ReactQuery<TResponse, TData = TResponse> {
  client: MarketplaceV2QueryClient;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface MarketplaceV2CollectionBidsByExpiryQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    queryOptions: QueryOptionsForCollectionBidExpiryOffset;
  };
}
export function useMarketplaceV2CollectionBidsByExpiryQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2CollectionBidsByExpiryQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2CollectionBidsByExpiry", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.collectionBidsByExpiry({
      queryOptions: args.queryOptions
    }),
    ...options
  });
}

export interface MarketplaceV2CollectionBidsByPriceQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    queryOptions: QueryOptionsForCollectionBidPriceOffset;
  };
}
export function useMarketplaceV2CollectionBidsByPriceQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2CollectionBidsByPriceQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2CollectionBidsByPrice", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.collectionBidsByPrice({
      queryOptions: args.queryOptions
    }),
    ...options
  });
}


export interface MarketplaceV2CollectionBidQuery<TData> extends MarketplaceV2ReactQuery<CollectionBidResponse, TData> {
  args: {
    bidder: string;
  };
}
export function useMarketplaceV2CollectionBidQuery<TData = CollectionBidResponse>({
  client,
  args,
  options
}: MarketplaceV2CollectionBidQuery<TData>) {
  return useQuery<CollectionBidResponse, Error, TData>({
    queryKey: ["marketplaceV2CollectionBid", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.collectionBid({
      bidder: args.bidder
    }),
    ...options
  });
}

export interface MarketplaceV2BidsByBidderExpiryQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    bidder: string;
    queryOptions: QueryOptionsForBidExpiryOffset;
  };
}
export function useMarketplaceV2BidsByBidderExpiryQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2BidsByBidderExpiryQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2BidsByBidderExpiry", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.bidsByBidderExpiry({
      bidder: args.bidder,
      queryOptions: args.queryOptions
    }),
    ...options
  });
}


export interface MarketplaceV2BidsByTokenPriceQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    queryOptions: QueryOptionsForBidTokenPriceOffset;
    tokenId: string;
  };
}
export function useMarketplaceV2BidsByTokenPriceQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2BidsByTokenPriceQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2BidsByTokenPrice", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.bidsByTokenPrice({
      queryOptions: args.queryOptions,
      tokenId: args.tokenId
    }),
    ...options
  });
}

export interface MarketplaceV2BidsSortedByExpiryQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    queryOptions: QueryOptionsForBidExpiryOffset;
  };
}
export function useMarketplaceV2BidsSortedByExpiryQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2BidsSortedByExpiryQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2BidsSortedByExpiry", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.bidsSortedByExpiry({
      queryOptions: args.queryOptions
    }),
    ...options
  });
}

export interface MarketplaceV2BidQuery<TData> extends MarketplaceV2ReactQuery<BidResponse, TData> {
  args: {
    bidder: string;
    tokenId: string;
  };
}
export function useMarketplaceV2BidQuery<TData = BidResponse>({
  client,
  args,
  options
}: MarketplaceV2BidQuery<TData>) {
  return useQuery<BidResponse, Error, TData>({
    queryKey: ["marketplaceV2Bid", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.bid({
      bidder: args.bidder,
      tokenId: args.tokenId
    }),
    ...options
  });
}

export interface MarketplaceV2AskCountQuery<TData> extends MarketplaceV2ReactQuery<AskCountResponse, TData> {}
export function useMarketplaceV2AskCountQuery<TData = AskCountResponse>({
  client,
  options
}: MarketplaceV2AskCountQuery<TData>) {
  return useQuery<AskCountResponse, Error, TData>({
    queryKey: ["marketplaceV2AskCount", client.contractAddress],
    queryFn: () => client.askCount(),
  });
}

export interface MarketplaceV2AsksBySellerExpiryQuery<TData> extends MarketplaceV2ReactQuery<AskResponse, TData> {
  args: {
    queryOptions: QueryOptionsForTokenTimestampOffset;
    seller: string;
  };
}
export function useMarketplaceV2AsksBySellerExpiryQuery<TData = AskResponse>({
  client,
  args,
  options
}: MarketplaceV2AsksBySellerExpiryQuery<TData>) {
  return useQuery<AskResponse, Error, TData>({
    queryKey: ["marketplaceV2AsksBySellerExpiry", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.asksBySellerExpiry({
      queryOptions: args.queryOptions,
      seller: args.seller
    }),
    ...options
  });
}

export interface MarketplaceV2AsksSortedByPriceQuery<TData> extends MarketplaceV2ReactQuery<AskResponse, TData> {
  args: {
    queryOptions: QueryOptionsForTokenPriceOffset;
  };
}
export function useMarketplaceV2AsksSortedByPriceQuery<TData = AskResponse>({
  client,
  args,
  options
}: MarketplaceV2AsksSortedByPriceQuery<TData>) {
  return useQuery<AskResponse, Error, TData>({
    queryKey: ["marketplaceV2AsksSortedByPrice", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.asksSortedByPrice({
      queryOptions: args.queryOptions
    }),
    ...options
  });
}

export interface MarketplaceV2AsksSortedByExpiryQuery<TData> extends MarketplaceV2ReactQuery<AskResponse, TData> {
  args: {
    queryOptions: QueryOptionsForTokenTimestampOffset;
  };
}
export function useMarketplaceV2AsksSortedByExpiryQuery<TData = AskResponse>({
  client,
  args,
  options
}: MarketplaceV2AsksSortedByExpiryQuery<TData>) {
  return useQuery<AskResponse, Error, TData>({
    queryKey: ["marketplaceV2AsksSortedByExpiry", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.asksSortedByExpiry({
      queryOptions: args.queryOptions
    }),
    ...options
  });
}


export interface MarketplaceV2AskQuery<TData> extends MarketplaceV2ReactQuery<AskResponse, TData> {
  args: {
    tokenId: string;
  };
}
export function useMarketplaceV2AskQuery<TData = AskResponse>({
  client,
  args,
  options
}: MarketplaceV2AskQuery<TData>) {
  return useQuery<AskResponse, Error, TData>({
    queryKey: ["marketplaceV2Ask", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.ask({
      tokenId: args.tokenId
    }),
    ...options
  });
}

export interface MarketplaceV2ConfigQuery<TData> extends MarketplaceV2ReactQuery<ConfigResponse, TData> {}
export function useMarketplaceV2ConfigQuery<TData = ConfigResponse>({
  client,
  options
}: MarketplaceV2ConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>({
    queryKey: ["marketplaceV2Config", client.contractAddress],
    queryFn: () => client.config(),
    ...options
  });
}
