/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Timestamp, Uint64, Uint128, ConfigResponse, Coin, Addr, Config, ExecuteMsg, AddMembersMsg, RemoveMembersMsg, HasEndedResponse, HasMemberResponse, HasStartedResponse, InstantiateMsg, IsActiveResponse, MembersResponse, QueryMsg } from "./Whitelist.types";
import { WhitelistQueryClient } from "./Whitelist.client";
export interface WhitelistReactQuery<TResponse, TData = TResponse> {
  client: WhitelistQueryClient;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface WhitelistConfigQuery<TData> extends WhitelistReactQuery<ConfigResponse, TData> {}
export function useWhitelistConfigQuery<TData = ConfigResponse>({
  client,
  options
}: WhitelistConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>({
    queryKey: ["whitelistConfig", client.contractAddress],
    queryFn: () => client.config(),
    ...options
  });
}

export interface WhitelistHasMemberQuery<TData> extends WhitelistReactQuery<HasMemberResponse, TData> {
  args: {
    member: string;
  };
}
export function useWhitelistHasMemberQuery<TData = HasMemberResponse>({
  client,
  args,
  options
}: WhitelistHasMemberQuery<TData>) {
  return useQuery<HasMemberResponse, Error, TData>({
    queryKey: ["whitelistHasMember", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.hasMember({
      member: args.member
    }),
    ...options
  });
}

export interface WhitelistMembersQuery<TData> extends WhitelistReactQuery<MembersResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useWhitelistMembersQuery<TData = MembersResponse>({
  client,
  args,
  options
}: WhitelistMembersQuery<TData>) {
  return useQuery<MembersResponse, Error, TData>({
    queryKey: ["whitelistMembers", client.contractAddress, JSON.stringify(args)],
    queryFn: () => client.members({
      limit: args.limit,
      startAfter: args.startAfter
    }),
    ...options
  });
}


export interface WhitelistIsActiveQuery<TData> extends WhitelistReactQuery<IsActiveResponse, TData> {}
export function useWhitelistIsActiveQuery<TData = IsActiveResponse>({
  client,
  options
}: WhitelistIsActiveQuery<TData>) {
  return useQuery<IsActiveResponse, Error, TData>({
    queryKey: ["whitelistIsActive", client.contractAddress],
    queryFn: () => client.isActive(),
    ...options
  });
}

export interface WhitelistHasEndedQuery<TData> extends WhitelistReactQuery<HasEndedResponse, TData> {}
export function useWhitelistHasEndedQuery<TData = HasEndedResponse>({
  client,
  options
}: WhitelistHasEndedQuery<TData>) {
  return useQuery<HasEndedResponse, Error, TData>({
    queryKey: ["whitelistHasEnded", client.contractAddress],
    queryFn: () => client.hasEnded(),
    ...options
  });
}
export interface WhitelistHasStartedQuery<TData> extends WhitelistReactQuery<HasStartedResponse, TData> {}
export function useWhitelistHasStartedQuery<TData = HasStartedResponse>({
  client,
  options
}: WhitelistHasStartedQuery<TData>) {
  return useQuery<HasStartedResponse, Error, TData>({
    queryKey: ["whitelistHasStarted", client.contractAddress],
    queryFn: () => client.hasStarted(),
    ...options
  });
}
